sudo: false

language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.0
    - android-24
    - extra-android-m2repository
    - extra-google-m2repository
    - sys-img-armeabi-v7a-android-19

before_install:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a --skin 480x800

install:
  - travis_retry travis_wait ./gradlew assembleDebug
  - emulator -avd test -no-audio -no-window &

before_script:
  - android-wait-for-emulator
  - sleep 30
  - adb shell input keyevent 82 &

script:
  - travis_wait 30 ./gradlew connectedCheck

after_script:
  - adb logcat -d
