sudo: false
language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.3
    - android-24
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'

before_install:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a --skin 480x800
  -  emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - sleep 28
  - adb shell input keyevent 82

after_script:
  - adb logcat -d

