sudo: false
language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.1
    - android-25
    - extra-android-m2repository

before_install:
  - sh scripts/emulator.sh
  - openssl aes-256-cbc -d -k "$FABRIC_PASSWORD" -in app/fabric.properties.enc -out app/fabric.properties

script:
  - travis_wait ./gradlew check

after_script:
  - adb logcat -d

after_success:
  - bash scripts/deploy_crashlytics.sh
  - bash <(curl -s https://codecov.io/bash)

notifications:
   slack:
    rooms:
      secure: hZT5nilAtnp7VdLvpmp8G4t21qO5Fuq5qMAjuzZK6GnJT5u7oE/MFpMvq9YGcXUkH0brLSOqe8Ri7wJqSfll2fDLY9dqzoQG9AUH3BP3I+sMtW5FnC08N9kd/oS+E6ZnjJ+xirQEkcYY5vBv0sBR92b1Q0xQzrxvdpkd5C0yWIfzcALoWfQvqsYf5PKzRU6fvtvLtLuXYEXI+G4n1aeEBrp/s4MZ6ZgTo9iOM9x9WwR3CS/nkRl9FENCNp+H15XZ+NjYfGs1lO18JLjktgPMUf5ITWLcRZPqFE2vTBTMdf6xni2LxXPXLw0RhSEZArmtKfe2XfjxHSI96R7kMeyBBBPsH9lLujxfu2k4kEIYOEPos0QejDrE1IcC2JGj7WKAJYv1X5cf0C5AEnCMsIdr4OQZYZV4n1R6qBYe+5NaHx++CruqqkVFLh9Xsoanz8xe8IiPwZsbbq7yeJb/wTYS/Y1YwTDg4RwCToUIFmQMD2UCuq/+7zvNYEcCwIeDn77BcRtW+wJS8FghClxHlhmfaZYAsf+CjeX7QrELJssfu9AepUvL90EuXEo/bWcdKp0/1U2tXO6S1T8U8G5yCUBxAbw1JIl0DYoVab4+eqdN6dI+Xyy1Zo176mJM5bZ78vmK0cfWUivbZ4pmgmRfK8iDXbnRhrsEZMWzvby9IFJCZZY=
    on_success: change
    on_failure: always
